spring.application.name=${SPRING_APPLICATION_NAME:product-service}

# ===============================
# SERVER
# ===============================
server.port=${SERVER_PORT:8085}

# ===============================
# MYSQL DATABASE
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}
spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT:org.hibernate.dialect.MySQL8Dialect}

# ===============================
# KAFKA
# ===============================
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

# ===============================
# REDIS
# ===============================
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework=${SPRING_LOG_LEVEL:INFO}
logging.level.com.yourpackage=${APP_LOG_LEVEL:DEBUG}

# ===============================
# CLOUDINARY
# ===============================
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}